config/routes.rb
Njaimh::Application.routes.draw do
  devise_for :users

  resources :practice_areas
  resources :endorsement_levels
  resources :members do
    get 'getExcel', :on => :collection
    post 'printExcel', :on => :collection
    get 'composeEmail', :on => :collection
    post 'sendEmail', :on => :collection
  end

     namespace :admin do
       root :to => "base#index"
       resources :users
     end

  root :to => 'homepage#index'

end

app/models/endorsement_level.rb
class EndorsementLevel < ActiveRecord::Base
  paginates_per 5
  attr_accessible :name
  validates :name, :presence => true
  validates_length_of :name, :maximum => 20
  validates_uniqueness_of :name
end

app/controllers/endorsement_levels_controller.rb
class EndorsementLevelsController < ApplicationController
  before_filter :authorize_admin!
  def index
    @endorsement_levels = EndorsementLevel.order("name").page(params[:page])
  end
  def new
    @endorsement_level = EndorsementLevel.new
    @submit_label = "Create"
  end
  def create
    @endorsement_level = EndorsementLevel.new(params[:endorsement_level])
    if @endorsement_level.save
      flash[:notice] = "Endorsement Level has been created."
      redirect_to @endorsement_level
    else
      flash[:notice] = "Endorsement Level has not been created."
      render :action => "new"
    end
  end
  def show
    @endorsement_level = EndorsementLevel.find(params[:id])
  end
  def edit
    @endorsement_level = EndorsementLevel.find(params[:id])
    @submit_label = "Update"
  end
  def update
    @endorsement_level = EndorsementLevel.find(params[:id])
    if @endorsement_level.update_attributes(params[:endorsement_level])
      flash[:notice] = "Endorsement Level has been updated."
      redirect_to @endorsement_level
    else
      flash[:notice] = "Endorsement Level has not been updated."
      render :action => "edit"
    end
  end
end

app/views/endorsement_levels/_form.html.erb
<%= form_for(@endorsement_level) do |f| %>
<%= f.error_messages %>
<p>
<%= f.label :name %>
<%= f.text_field :name %>
</p>
<%= f.submit @submit_label, :class => "btn btn-primary btn-large" %>
<% end %>

app/views/endorsement_levels/edit.html.erb
<h2>Edit endorsement level</h2>
<%= render "form" %>
<%= link_to "Cancel", endorsement_level_path(@endorsement_level), :class => "btn btn-primary btn-large" %>

app/views/endorsement_levels/index.html.erb
<%= link_to "New Endorsement Level", new_endorsement_level_path, :class => "btn btn-primary btn-large" %>
<h2>Endorsement Levels</h2>
<%= paginate @endorsement_levels %>
<ul>
<% @endorsement_levels.each do |endorsement_level| %>
<li><%= link_to endorsement_level.name, endorsement_level %></li>
<% end %>
</ul>
<%= link_to "Return to Admin Top", admin_root_path, :class => "btn btn-primary btn-large" %>

app/views/endorsement_levels/new.html.erb
<h2>New Endorsement Level</h2>
<%= render "form" %>
<%= link_to "Cancel", endorsement_levels_path, :class => "btn btn-primary btn-large" %>

app/views/endorsement_levels/show.html.erb
<h2><%= @endorsement_level.name %></h2>
<%= link_to "Edit Endorsement Level", edit_endorsement_level_path(@endorsement_level), :class => "btn btn-primary btn-large" %>
<%= link_to "Return to All Endorsement Levels", endorsement_levels_path, :class => "btn btn-primary btn-large" %>