config/routes.rb
Njaimh::Application.routes.draw do
  devise_for :users

  resources :practice_areas
  resources :endorsement_levels
  resources :members do
    get 'getExcel', :on => :collection
    post 'printExcel', :on => :collection
    get 'composeEmail', :on => :collection
    post 'sendEmail', :on => :collection
  end

     namespace :admin do
       root :to => "base#index"
       resources :users
     end

  root :to => 'homepage#index'

end

app/models/practice_area.rb
class PracticeArea < ActiveRecord::Base
  paginates_per 5
  attr_accessible :name
  validates :name, :presence => true
  validates_length_of :name, :maximum => 20
  validates_uniqueness_of :name
end

app/controllers/practice_areas_controller.rb
class PracticeAreasController < ApplicationController
  before_filter :authorize_admin!
  def index
    @practice_areas = PracticeArea.order("name").page(params[:page])
  end
  def new
    @practice_area = PracticeArea.new
    @submit_label = "Create"
  end
  def create
    @practice_area = PracticeArea.new(params[:practice_area])
    if @practice_area.save
      flash[:notice] = "Practice Area has been created."
      redirect_to @practice_area
    else
      flash[:notice] = "Practice Area has not been created."
      render :action => "new"
    end
  end
  def show
    @practice_area = PracticeArea.find(params[:id])
  end
  def edit
    @practice_area = PracticeArea.find(params[:id])
    @submit_label = "Update"
  end
  def update
    @practice_area = PracticeArea.find(params[:id])
    if @practice_area.update_attributes(params[:practice_area])
      flash[:notice] = "Practice Area has been updated."
      redirect_to @practice_area
    else
      flash[:notice] = "Practice Area has not been updated."
      render :action => "edit"
    end
  end
end

app/views/practice_areas/_form.html.erb
<%= form_for(@practice_area) do |f| %>
<%= f.error_messages %>
<p>
<%= f.label :name %>
<%= f.text_field :name %>
</p>
<%= f.submit @submit_label, :class => "btn btn-primary btn-large" %>
<% end %>

app/views/practice_areas/edit.html.erb
<h2>Edit practice area</h2>
<%= render "form" %>
<%= link_to "Cancel", practice_area_path(@practice_area), :class => "btn btn-primary btn-large" %>

app/views/practice_areas/index.html.erb
<%= link_to "New Practice Area", new_practice_area_path, :class => "btn btn-primary btn-large" %>
<h2>Practice Areas</h2>
<%= paginate @practice_areas %>
<ul>
<% @practice_areas.each do |practice_area| %>
<li><%= link_to practice_area.name, practice_area %></li>
<% end %>
</ul>
<%= link_to "Return to Admin Top", admin_root_path, :class => "btn btn-primary btn-large" %>

app/views/practice_areas/new.html.erb
<h2>New Practice Area</h2>
<%= render "form" %>
<%= link_to "Cancel", practice_areas_path, :class => "btn btn-primary btn-large" %>

app/views/practice_areas/show.html.erb
<h2><%= @practice_area.name %></h2>
<%= link_to "Edit Practice Area", edit_practice_area_path(@practice_area), :class => "btn btn-primary btn-large" %>
<%= link_to "Return to All Practice Areas", practice_areas_path, :class => "btn btn-primary btn-large" %>