config/routes.rb
Njaimh::Application.routes.draw do
  devise_for :users

  resources :practice_areas
  resources :endorsement_levels
  resources :members do
    get 'getExcel', :on => :collection
    post 'printExcel', :on => :collection
    get 'composeEmail', :on => :collection
    post 'sendEmail', :on => :collection
  end

     namespace :admin do
       root :to => "base#index"
       resources :users
     end

  root :to => 'homepage#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
  paginates_per 12
  belongs_to :practice_area
  belongs_to :endorsement_level
  attr_accessible :address_1, :address_2, :agency, :board_member, :city, :email_1, :email_2, :first_name, :home_phone, :last_name, :state, :work_phone, :zip, :memo, :board_position, :fax_number, :org_member, :county, :dues_paid_year, :org_member_type, :work_extension, :title_credential, :practice_area_id, :secondary_practice_area_id, :endorsement_level_id
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates_length_of :first_name, :maximum => 16
  validates_length_of :last_name, :maximum => 20
  validate :work_phone_may_not_have_alphas, :home_phone_may_not_have_alphas, :fax_number_may_not_have_alphas, :primary_email_must_have_at_sign, :secondary_email_must_have_at_sign, :work_extension_may_not_have_alphas, :dues_paid_year_may_not_have_alphas
  validates :home_phone, :phone => true
  validates :work_phone, :phone => true
  scope :by_last_name, (lambda do |last_name| { :conditions => ['last_name LIKE ?', "%#{last_name}%"]} end)
  scope :members_only, where(:org_member => true)
  scope :board_only, where(:board_member => true)
  scope :emailers, where("email_1 <> ''")
  scope :sort_last_name, order(:last_name)
  scope :by_agency, (lambda do |agency| { :conditions => ['agency LIKE ?', "%#{agency}%"]} end)
  scope :by_first_name, (lambda do |first_name| { :conditions => ['first_name LIKE ?', "%#{first_name}%"]} end)
  def full
    "#{first_name} #{last_name}"
  end
  def print_home_phone
    home_phone =~ /\d/ ? "#{home_phone}" : "-"
  end
  def print_work_phone
    work_phone =~ /\d/ ? "#{work_phone}" : "-"
  end
  def print_agency
    agency =~ /\w/ ? "#{agency}" : "-"
  end
  def print_email_1
    email_1 =~ /\w/ ? "#{email_1}" : "-"
  end
  def print_email_2
    email_2 =~ /\w/ ? "#{email_2}" : "-"
  end
  def print_address_1
    address_1 =~ /\w/ ? "#{address_1}" : "-"
  end
  def print_address_2
    address_2 =~ /\w/ ? "#{address_2}" : "-"
  end
  def print_city
    city =~ /\w/ ? "#{city}" : "-"
  end
  def print_state
    state =~ /\w/ ? "#{state}" : "-"
  end
  def print_board_member
    board_member ? "Y" : "N"
  end
  def print_board_position
    board_position =~ /\w/ ? "#{board_position}" : "-"
  end
  def print_fax_number
    fax_number =~ /\d/ ? "#{fax_number}" : "-"
  end
  def print_memo
    memo =~ /\w/ ? "#{memo}" : "-"
  end
  def print_org_member
    org_member ? "Y" : "N"
  end
  def print_work_extension
    work_extension =~ /\d/ ? "#{work_extension}" : "-"
  end
  def print_title_credential
    title_credential =~ /\w/ ? "#{title_credential}" : "-"
  end
  def print_title_credential_csv
    if title_credential =~ /\w/
      title_credential.gsub!(/,/, ';')
      "#{title_credential}"
    else
      "-"
    end
  end
  def print_county
    county =~ /\w/ ? "#{county}" : "-"
  end
  def print_org_member_type
    org_member_type =~ /\w/ ? "#{org_member_type}" : "-"
  end
  def print_dues_paid_year
    dues_paid_year =~ /\d/ ? "#{dues_paid_year}" : "-"
  end
  def print_practice_area
    if not practice_area_id.nil?
      return PracticeArea.find(practice_area_id).name
    else
      return "-"
    end
  end
  def print_secondary_practice_area
    if not secondary_practice_area_id.nil?
      return PracticeArea.find(secondary_practice_area_id).name
    else
      return "-"
    end
  end
  def print_endorsement_level
    if not endorsement_level_id.nil?
      return EndorsementLevel.find(endorsement_level_id).name
    else
      return "-"
    end
  end
  def work_phone_may_not_have_alphas
    if work_phone =~ /[a-zA-Z]/
      errors.add(:work_phone, "may not have letters")
    end
  end
  def work_extension_may_not_have_alphas
    errors.add(:work_extension, "may not have letters") if work_extension =~ /[a-zA-Z]/
  end
  def dues_paid_year_may_not_have_alphas
    errors.add(:dues_paid_year, "may not have letters") if dues_paid_year =~ /[a-zA-Z]/
  end
  def home_phone_may_not_have_alphas
    if home_phone =~ /[a-zA-Z]/
      errors.add(:home_phone, "may not have letters")
    end
  end
  def fax_number_may_not_have_alphas
    if fax_number =~ /[a-zA-Z]/
      errors.add(:fax_number, "may not have letters")
    end
  end
  def primary_email_must_have_at_sign
    if email_1.length > 0 and email_1 !~ /\@/
      errors.add(:primary_email, "must have \@ sign")
    end
  end
  def secondary_email_must_have_at_sign
    if email_2.length > 0 and email_2 !~ /\@/
      errors.add(:secondary_email, "must have \@ sign")
    end
  end
end

app/controllers/members_controller.rb
require 'csv'
class MembersController < ApplicationController
  before_filter :authorize_admin!
  def new
    @member = Member.new
    @submit_label = "Create"
  end
  def create
    @member = Member.new(params[:member])
    if @member.save
      flash[:notice] = "Contact has been created."
      redirect_to @member
    else
      flash[:notice] = "Contact has not been created."
      render :action => "new"
    end
  end
  def index
    l = params[:agency_clue]
    f = params[:first_name_clue]
    @members = Member.sort_last_name.by_agency(l).by_first_name(f).page(params[:page])
   
    if not params[:member_last_name].nil?
      @members = Member.sort_last_name.by_agency(l).by_first_name(f).by_last_name(params[:member_last_name]).page(params[:page])
    end
    #@members = Member.search params[:search], :order => :last_name, :page => params[:page], :per_page => 10
    #@last_names = Member.all.map(&:last_name)
    @last_names = Member.find(:all,:conditions => ['last_name LIKE ?', "#{params[:term]}%"]).map(&:last_name)
    respond_to do |format|
      format.html
      format.json { render :json => @last_names }
    end
  end
  def show
    @member = Member.find(params[:id])
  end
  def edit
    @member = Member.find(params[:id])
    @submit_label = "Update"
  end
  def update
    @member = Member.find(params[:id])
    if @member.update_attributes(params[:member])
      flash[:notice] = "Contact has been updated."
      redirect_to @member
    else
      flash[:notice] = "Contact has not been updated."
      redirect_to :action => "edit"
    end
  end
  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    flash[:notice] = "Contact has been deleted."
    redirect_to members_path
  end
  def sendEmail
    # be sure to render the HTML properly
    @email_text = params[:email_setup]["email_text"].gsub(/\n/, '<br/>').html_safe
    @subject = params[:email_setup]["subject"]
    # This object will have attributes specifying the attachment.
    uploaded_io = params[:email_setup]["file_attachment"]
    uploaded_data = ""
    uploaded_filename = ""
    if uploaded_io != nil
      # Get the data itself, and the filename
      uploaded_data = uploaded_io.read
      uploaded_filename = uploaded_io.original_filename
    end
    everyone = params[:email_setup]["everyone"].to_i
    members_only = params[:email_setup]["members_only"].to_i
    board_only = params[:email_setup]["board_only"].to_i

    @recipients = Member.emailers.map(&:email_1) if everyone == 1
    @recipients = Member.members_only.map(&:email_1).compact if members_only == 1
    @recipients = Member.board_only.map(&:email_1).compact if board_only == 1
    NJAIMHMailer.send_email(@email_text,@subject,@recipients,uploaded_filename,uploaded_data).deliver
    redirect_to :action => "index"
  end
  def printExcel
    @o_format = params[:stuff_select]["o_format"]
    @members_only = params[:stuff_select]["members_only"].to_i
    @board_only = params[:stuff_select]["board_only"].to_i
    @file_name = "njaimh_members"
    @legend = "All Contacts Report"
    @data = Hash.new
    members = Member.find(:all)
    members = Member.members_only if @members_only == 1
    members = Member.board_only if @board_only == 1
    for m in members
      key = "#{m.last_name},#{m.first_name},#{m.address_1},#{m.address_2},#{m.city},#{m.county},#{m.state},#{m.zip},#{m.work_phone},#{m.work_extension},#{m.fax_number},#{m.home_phone},#{m.email_1},#{m.email_2},#{m.dues_paid_year},#{m.print_title_credential_csv},#{m.print_org_member},#{m.print_org_member_type},#{m.print_board_member},#{m.print_board_position},#{m.print_practice_area},#{m.print_secondary_practice_area},#{m.print_endorsement_level}"
      @data[key] = m.agency
    end
    @csv_header = ["Last Name", "First Name", "Address_1", "Address_2", "City", "County", "State", "Zip", "Work Phone","Extension","Fax Number","Home/Cell Phone","Primary Email Address", "Secondary Email Address", "Dues Paid", "Title/Credential", "Member?", "MemberType", "Board?","BoardPosition","PracticeArea","SecondaryPracticeArea","EndorsementLevel","Agency"]
    printCsv
  end
private
  def printCsv
    if @o_format == "CSV"
      csv_string = CSV.generate do |csv|
        csv << @csv_header
        @data.sort.each do |i|
          m = i[0].split(',')
          m << i[1]
          csv << m
        end
      end
      send_data csv_string, :type => "text/csv", :filename => "#{@file_name}.csv"
    else
      pdf = Prawn::Document.new
      x_out = DateTime.now.strftime("%B %d, %Y")
      pdf.font_size 20
      pdf.text "Franklin Township Food Bank", :align => :center
      pdf.font_size 10
      pdf.text "PO Box 333", :align => :center
      pdf.text "60 Millstone Road", :align => :center
      pdf.text "Somerset, NJ 08875-0333", :align => :center
      pdf.text "Telephone: (732) 246-0009", :align => :center
      pdf.text "email: fhasner@ftfb.us", :align => :center
      pdf.text "Website: http://www.franklinfoodbank.org", :align => :center
      pdf.font_size 14
      pdf.move_down 10
      pdf.text "Report Date: #{x_out}", :align => :center
      pdf.move_down 40
      pdf.font_size 20 
      pdf.text @legend, :align => :center
      pdf.move_down 20
      pdf.font_size 14
      table_out = []
      table_out << @csv_header
      @data.sort.each do |i|
        m = i[0].split(',')
        m << i[1]
        table_out << m
      end
      pdf.table table_out
      send_data pdf.render, :type => "application/pdf", :filename => "#{@file_name}.pdf"
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
<%= f.error_messages %>
<table>
<tr>
<td><%= f.label :first_name, "First Name" %></td>
<td><%= f.text_field :first_name %></td>
<td><%= f.label :last_name, "Last Name" %></td>
<td><%= f.text_field :last_name %></td>
</tr>
<tr>
<td><%= f.label :agency %></td>
<td><%= f.text_field :agency %></td>
<td><%= f.label :fax_number, "Fax Number" %></td>
<td><%= f.text_field :fax_number %></td>
</tr>
<tr>
<td><%= f.label :primary_email, "Primary Email" %></td>
<td><%= f.text_field :email_1 %></td>
<td><%= f.label :secondary_email, "Secondary Email" %></td>
<td><%= f.text_field :email_2 %></td>
</tr>
<tr>
<td><%= f.label :work_phone, "Work Phone" %></td>
<td><%= f.text_field :work_phone %></td>
<td><%= f.label :work_extension, "Work Extension" %></td>
<td><%= f.text_field :work_extension %></td>
</tr>
<tr>
<td><%= f.label :home_phone, "Home/Cell Phone" %></td>
<td><%= f.text_field :home_phone %></td>
</tr>
<tr>
<td><%= f.label :address_1 %></td>
<td><%= f.text_field :address_1 %></td>
<td><%= f.label :address_2 %></td>
<td><%= f.text_field :address_2 %></td>
</tr>
<tr>
<td><%= f.label :city %></td>
<td><%= f.text_field :city %></td>
<td><%= f.label :county %></td>
<td><%= f.text_field :county %></td>
</tr>
<tr>
<td><%= f.label :state %></td>
<td><%= f.text_field :state %></td>
<td><%= f.label :zip %></td>
<td><%= f.text_field :zip %></td>
</tr>
<tr>
<td><%= f.label :org_member, "Org Member" %></td>
<% if @member.org_member %>
<td><%= f.radio_button :org_member, :true, :checked => true  %>Yes</td>
<td><%= f.radio_button :org_member, :false %>No</td>
<% else %>
<td><%= f.radio_button :org_member, :true %>Yes</td>
<td><%= f.radio_button :org_member, :false, :checked => true %>No</td>
<% end %>
</tr>
<tr>
<td><%= f.label :org_member_type, "Org Member Type" %></td>
<td><%= f.text_field :org_member_type %></td>
<td><%= f.label :dues_paid_year, "Dues Paid Year" %></td>
<td><%= f.text_field :dues_paid_year %></td>
</tr>
<tr>
<td><%= f.label :board_member, "Board Member" %></td>
<% if @member.board_member %>
<td><%= f.radio_button :board_member, :true, :checked => true  %>Yes</td>
<td><%= f.radio_button :board_member, :false %>No</td>
<% else %>
<td><%= f.radio_button :board_member, :true %>Yes</td>
<td><%= f.radio_button :board_member, :false, :checked => true %>No</td>
<% end %>
</tr>
<tr>
<td><%= f.label :board_position, "Board Position" %></td>
<td><%= f.text_field :board_position, :size => 60 %></td>
</tr>
<tr>
<td><%= f.label :title_credential, "Title/Credential" %></td>
<td><%= f.text_field :title_credential, :size => 60 %></td>
</tr>
<tr>
<td><%= f.label :memo %></td>
<td><%= f.text_field :memo, :size => 60 %></td>
</tr>
<tr>
<td><%= f.label :practice_area, "Practice Area" %><br /></td>
<td><%= f.collection_select(:practice_area_id, PracticeArea.find(:all, :order => :name), :id, :name, { :prompt => "-- Select --" }) %></td>
<td><%= f.label :endorsement_level, "Endorsement Level" %><br /></td>
<td><%= f.collection_select(:endorsement_level_id, EndorsementLevel.find(:all, :order => :name), :id, :name, { :prompt => "-- Select --" }) %></td>
</tr>
<tr>
<td><%= f.label :secondary_practice_area, "Secondary Practice Area" %><br /></td>
<td><%= f.collection_select(:secondary_practice_area_id, PracticeArea.find(:all, :order => :name), :id, :name, { :prompt => "-- Select --" }) %></td>
</tr>

</table>
<%= f.submit @submit_label, :class => 'btn btn-primary btn-large' %>
<% end %>

app/views/members/_members_list.html.erb
<ul id='members'>
<% @members.each do |member| %>
<%= content_tag_for(:li, member, :data => { :agency => member.agency, :county => member.county }) do %>
  <%= link_to member.full, member %>
<% end %>
<% end %>
</ul>

app/views/members/composeEmail.html.erb
<h1>Compose Email</h1>
<div class="form">
<%= form_for :email_setup, :url => { :action => "sendEmail" } do |f| %>
<div>
<%= f.label :subject %>
<%= f.text_field :subject, :size => 72 %>
</div>
<div>
<%= f.label :file_attachment %>
<%= f.file_field :file_attachment %>
</div>
<div>
<%= f.label :email_text %>
<%= f.text_area :email_text, :cols => 76, :rows => 20 %>
</div>
<%= f.check_box :everyone %>All Contacts
<br>
<%= f.check_box :members_only %>Members Only
<br>
<%= f.check_box :board_only %>Board Only
<br>
<%= submit_tag "Send" %>
</div>
<% end %>

app/views/members/edit.html.erb
<h2>Edit Contact</h2>
<%= render "form" %>
<%= link_to "Cancel", @member, :class => "btn btn-primary btn-large" %>

app/views/members/getExcel.html.erb
<h1>Contact Report</h1>
<div class="form">
<%= form_for :stuff_select, :url => { :action => "printExcel" } do |f| %>
<div>
<%= f.radio_button :o_format, :CSV, :checked => true %>CSV<BR>
<%= f.radio_button :o_format, :PDF %>PDF<BR>
</div>
<%= f.check_box :members_only %>Members Only
<br>
<%= f.check_box :board_only %>Board Only
<br>
<%= submit_tag "Go!" %>
</div>
<% end %>

app/views/members/index.html.erb
<% if user_signed_in? %>
<%= link_to "New Contact", new_member_path, :class => "btn btn-primary btn-large" %>
<% end %>
<h2>Contacts</h2>
<%= form_tag members_path, :method => :get do %>
<%= label_tag "Search by Last Name" %>
<%= text_field_tag :member_last_name, nil, :class => 'member_last_name' %>
<%= label_tag "First Name Clue:" %>
<%= text_field_tag :first_name_clue, nil, :class => 'first_name_clue' %>
<%= label_tag "Agency Clue:" %>
<%= text_field_tag :agency_clue, nil, :class => 'agency_clue' %>
<%= submit_tag "Go!", :name => nil %>
<% end %>
<div id="members">
<% if @members.size == 0 %>
<h2>Search produced 0 results</h2>
<% else %>
<%= paginate @members %>
<%= render :partial => "members_list" %>
<% end %>
</div>
<% if user_signed_in? %>
<%= link_to "PrintExcelListing", :action => "getExcel", :controller => "members", :class => "btn btn-primary btn-large" %>
<%= link_to "ComposeEmail", :action => "composeEmail", :controller => "members", :class => "btn btn-primary btn-large" %>
<% end %>
<div id='tip' style='display:none'>
</div>

app/views/members/index.js.erb
<%= raw @last_names %>

app/views/members/new.html.erb
<h2>New Contact</h2>
<%= render "form" %>
<%= link_to "Cancel", members_path, :class => "btn btn-primary btn-large" %>

app/views/members/show.html.erb
<h2><%= @member.full %></h2>
<table>
<tr>
<td>First Name</td>
<td><b><%= @member.first_name %></b></td>
</tr>
<tr>
<td>Last Name</td>
<td><b><%= @member.last_name %></b></td>
</tr>
<tr>
<td>Agency</td>
<td><b><%= @member.print_agency %></b></td>
</tr>
<tr>
<td>Primary Email</td>
<td><b><%= @member.print_email_1 %></b></td>
</tr>
<tr>
<td>Secondary Email</td>
<td><b><%= @member.print_email_2 %></b></td>
</tr>
<tr>
<td>Work Phone</td><td><b><%= @member.print_work_phone %></b></td>
<td>Work Extension</td><td><b><%= @member.print_work_extension %></b></td>
</tr>
<tr>
<td>Fax Number</td>
<td><b><%= @member.print_fax_number %></b></td>
</tr>
<tr>
<td>Home/Cell Phone</td>
<td><b><%= @member.print_home_phone %></b></td>
</tr>
<tr>
<td>Address</td>
<td><b><%= @member.print_address_1 %></b></td>
</tr>
<tr>
<td>Address</td>
<td><b><%= @member.print_address_2 %></b></td>
</tr>
<tr>
<td>City</td><td><b><%= @member.print_city %></b></td>
</tr>
<tr>
<td>County</td><td><b><%= @member.print_county %></b></td>
</tr>
<tr>
<td>State</td><td><b><%= @member.print_state %></b></td>
</tr>
<tr>
<td>Zip</td><td><b><%= @member.zip %></b></td>
</tr>
<tr>
<td>Org Member?</td><td><b><%= @member.print_org_member %></b></td>
<td>Member Type</td>
<td><b><%= @member.print_org_member_type %></b></td>
</tr>
<tr>
<td>Board Member?</td><td><b><%= @member.print_board_member %></b></td>
<td>Board Position</td>
<td><b><%= @member.print_board_position %></b></td>
</tr>
<tr>
<td>Dues Paid Year</td>
<td><b><%= @member.print_dues_paid_year %></b></td>
</tr>
<tr>
<td>Title/Credential</td>
<td><b><%= @member.print_title_credential %></b></td>
</tr>
<tr>
<td>Practice Area</td>
<td><b><%= @member.print_practice_area %></b></td>
</tr>
<tr>
<td>Secondary Practice Area</td>
<td><b><%= @member.print_secondary_practice_area %></b></td>
</tr>
<tr>
<td>Endorsement Level</td>
<td><b><%= @member.print_endorsement_level %></b></td>
</tr>
<tr>
<td>Memo</td>
<td><b><%= @member.print_memo %></b></td>
</tr>
</table>
<% if user_signed_in? %>
<%= link_to "Edit Contact", edit_member_path(@member), :class => "btn btn-primary btn-large" %>
<% end %>
<%= link_to "Return to All Contacts", members_path, :class => "btn btn-primary btn-large" %>
<% if user_signed_in? %>
<%= link_to "Delete Contact", @member, :method => :delete,
  :confirm => "Are you sure you want to delete this contact?", :class => "btn btn-primary btn-large" %>
<% end %>